apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: wordpress
data:
  MYSQL_ROOT_PASSWORD: "wordpress"
  MYSQL_DATABASE: "wordpress"
  MYSQL_USER: "wpuser"
  MYSQL_PASSWORD: "wppass"
